services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
  redis:
    image: redis:latest
    expose:
      - "6379"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reukvheo1
      POSTGRES_DB: asiamotors1

    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  java:
    build: .
    ports:
      - "8000:1010"



